### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device 

### ISSUE THREAD

**Issue by studabyd** [M3DV/AlignShift#3]
Hello, I run the test code and have the problem:
RuntimeError: CUDA error: no kernel image is available for execution on the device (launch_kernel at /pytorch/aten/src/ATen/native/cuda/Loops.cuh:102)
frame #0: c10::Error::Error(
[2020-10-23 12-07-11屏幕截图](https://user-images.githubusercontent.com/52878967/96955554-70c89200-1528-11eb-8549-40d1501bd1c1.png)

so do you know how to solve it. And what is the cuda version do you use. Thank you!

**Comment by studabyd** [comment]
The error above happend when I evaluate in TiTAN X GPU, but disappeared in Geforcr GTX 1660 GPU, （they have diffirent environments in different computers）.

**Comment by NotF404** [comment]
hi
     sorry for late replay, we updated  setup.py and README. now you can follow installation in README to compile mmdet's operations in you own environments. this operations that are the causes of your problem are compiled differently  in different environments.

**Comment by studabyd** [comment]
> hi
> sorry for late replay, we updated setup.py and README. now you can follow installation in README to compile mmdet's operations in you own environments. this operations that are the causes of your problem are compiled differently in different environments.

Hello, thank you for your reply and update. I try your new 'readme.md' file and do 'python setup.py install' before run test code, but the same error happened. My computer has 2 GPUs:TiTan Xp and TiTanx, in which the error happened but I run the test code successfully in Geforcr GTX 1660 GPU. So whether the GPU is the reason, or I run it in the wrong way? What files such as 'build,*.eggs' I should delete before setup.py. I see the setup.py file, and the 'ext_module' about nms_cuda in 170 line of setup.py maybe has something wrong. The following is error picture and my environment.
![2020-10-23 12-07-11屏幕截图](https://user-images.githubusercontent.com/52878967/97316946-4880c080-18a5-11eb-9507-7146bc7a9426.png)

My computer environment:
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
NVCC: Cuda compilation tools, release 9.0, V9.0.176
GPU 0: TITAN X (Pascal)
GPU 1: TITAN Xp
GCC: gcc (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4
PyTorch: 1.3.0
torchvision:0.4.1
mmcv:0.2.15
mmdet:1.0rc1+277b5dc

**Comment by NotF404** [comment]
You can install official mmdetection and follow [here](https://github.com/M3DV/AlignShift/blob/master/mmdet/README.md) to add you code in mmdet, if it's the case.

**Comment by studabyd** [comment]
> You can install official mmdetection and follow [here](https://github.com/M3DV/AlignShift/blob/master/mmdet/README.md) to add you code in mmdet, if it's the case.
Ok, I will try it, Thank you.
